version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  banking-api:
    image: banking/banking-api:0.0.1
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/postgres
      R2DBC_URL: r2dbc:postgresql://postgres:5432/postgres
      DB_USER: user
      DB_PASSWORD: password

volumes:
  postgres_data:
