spring:
  r2dbc:
    url: ${R2DBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
  flyway:
    url: ${JDBC_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    locations: classpath:db/migration

resilience4j:
  retry:
    instances:
      create-transaction:
        retry-exceptions:
          - org.springframework.dao.OptimisticLockingFailureException
        max-attempts: 3
        wait-duration: 100ms
